sudo: false
language: java
jdk: openjdk11

services:
  - docker

script:
  - ./gradlew clean spotlessCheck build codeCoverageReport buildImage composeUp postman composeDown pushImage --stacktrace --info

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r build/reports/jacoco/report.xml