sudo: false
language: java
jdk: openjdk11

services:
  - docker

script:
  - ./gradlew clean spotlessCheck build buildImage composeUp postman composeDown

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew jacocoRootReport coveralls